import 'dart:math';
import 'package:flutter/material.dart';

class GradientPage extends StatelessWidget { const GradientPage({super.key,required this.child}); final Widget child; @override Widget build(BuildContext c)=>Container(width:double.infinity,height:double.infinity,decoration:BoxDecoration(gradient:RadialGradient(radius:1.1,center:Alignment.topCenter,colors:[Theme.of(c).colorScheme.primary.withValues(alpha:.10),Theme.of(c).scaffoldBackgroundColor])),child:SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(20),child:Center(child:child))));}
class GlassCard extends StatelessWidget { const GlassCard({super.key,required this.child,this.padding=const EdgeInsets.all(16)}); final Widget child; final EdgeInsets padding; @override Widget build(BuildContext c)=>Container(padding:padding,decoration:BoxDecoration(color:Theme.of(c).colorScheme.surface,borderRadius:BorderRadius.circular(24),border:Border.all(color:Theme.of(c).colorScheme.outline),boxShadow:[BoxShadow(color:Theme.of(c).colorScheme.shadow.withValues(alpha:.08),blurRadius:12,offset:const Offset(0,3))]),child:child);}
class BrandHeader extends StatelessWidget { const BrandHeader({super.key}); @override Widget build(BuildContext c)=>Row(mainAxisAlignment:MainAxisAlignment.center,children:[Container(width:48,height:48,decoration:BoxDecoration(color:Theme.of(c).colorScheme.primary,borderRadius:BorderRadius.circular(14)),alignment:Alignment.center,child:const Text('Є',style:TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w800))),const SizedBox(width:10),Text('Є-Гідність',style:Theme.of(c).textTheme.headlineSmall!.copyWith(fontWeight:FontWeight.w800))]);}
class ChoiceCard extends StatelessWidget { const ChoiceCard({super.key,required this.icon,required this.title,required this.subtitle,required this.onTap}); final IconData icon; final String title,subtitle; final VoidCallback onTap; @override Widget build(BuildContext c)=>InkWell(borderRadius:BorderRadius.circular(18),onTap:onTap,child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(border:Border.all(color:Theme.of(c).colorScheme.outline),borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[CircleAvatar(backgroundColor:Theme.of(c).colorScheme.surfaceContainerHighest,child:Icon(icon,color:Theme.of(c).colorScheme.primary)),const SizedBox(height:10),Text(title,style:const TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:4),Text(subtitle,style:Theme.of(c).textTheme.bodySmall)])));}
class InfoCard extends StatelessWidget { const InfoCard({super.key,required this.title,required this.rows}); final String title; final Map<String,String> rows; @override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Theme.of(c).colorScheme.surface,border:Border.all(color:Theme.of(c).colorScheme.outline),borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.w700)),...rows.entries.map((e)=>Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(e.key,style:TextStyle(color:Theme.of(c).colorScheme.onSurfaceVariant)),Flexible(child:Text(e.value,style:const TextStyle(fontWeight:FontWeight.w600),textAlign:TextAlign.right))]))) ]));}
class DiiaQr extends StatelessWidget { const DiiaQr({super.key}); @override Widget build(BuildContext c)=>Container(width:220,height:220,padding:20,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:CustomPaint(painter:_QrPainter()));}
class _QrPainter extends CustomPainter { @override void paint(Canvas canvas,Size size){final p=Paint()..color=Colors.black; final r=Random(7); final n=11; final s=size.width/n; for(int y=0;y<n;y++){for(int x=0;x<n;x++){if(r.nextBool())canvas.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(x*s,y*s,s-2,s-2),const Radius.circular(1)),p);}}} @override bool shouldRepaint(covariant CustomPainter old)=>false;}
class IdCard extends StatelessWidget { const IdCard({super.key}); @override Widget build(BuildContext c)=>Container(width:double.infinity,padding:const EdgeInsets.all(18),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Colors.black,Color(0xFF1257A6)]),borderRadius:BorderRadius.circular(18)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('Є-ГІДНІСТЬ',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800)),Icon(Icons.credit_card,color:Color(0xFFD7B84D))]),SizedBox(height:20),Row(children:[CircleAvatar(radius:28,child:Text('ОК')),SizedBox(width:12),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Олексій Коваль',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800)),Text('Педагог · Школа №1',style:TextStyle(color:Colors.white70))])]),SizedBox(height:16),Text('✓ ПІДТВЕРДЖЕНО',style:TextStyle(color:Color(0xFF6EE7A8),fontWeight:FontWeight.w800))]));}
