import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../providers/app_providers.dart';

class ProfileScreen extends ConsumerWidget { const ProfileScreen({super.key}); @override Widget build(BuildContext c,WidgetRef ref){final u=ref.watch(authProvider)!; return ListView(padding:const EdgeInsets.all(24),children:[
  Text('Профіль',style:Theme.of(c).textTheme.headlineSmall!.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:16),
  Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Colors.black,Color(0xFF1257A6)]),borderRadius:BorderRadius.circular(20)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('Є-ГІДНІСТЬ',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800)),Icon(Icons.credit_card,color:Color(0xFFD7B84D))]),const SizedBox(height:20),Row(children:[const CircleAvatar(radius:30,child:Text('ОК')),const SizedBox(width:12),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Олексій Коваль',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800)),Text('8-Б • Школа №1',style:TextStyle(color:Colors.white70))])]),const SizedBox(height:14),Text('✓ ${u.diiaVerified?'ПІДТВЕРДЖЕНО ЧЕРЕЗ ДІЮ':'ДЕМО'}',style:const TextStyle(color:Color(0xFF6EE7A8),fontWeight:FontWeight.w800))]),
  const SizedBox(height:16),ListTile(leading:const Icon(Icons.settings_outlined),title:const Text('Налаштування'),onTap:()=>context.go('/home/profile/settings')),ListTile(leading:const Icon(Icons.security_outlined),title:const Text('Безпека'),onTap:()=>context.go('/home/profile/security')),ListTile(leading:const Icon(Icons.qr_code_2),title:const Text('Мій QR'),onTap:()=>context.go('/home/profile/qr')),if(u.role==UserRole.teacher||u.role==UserRole.admin)ListTile(leading:const Icon(Icons.qr_code_scanner),title:const Text('Сканувати QR'),onTap:()=>context.go('/home/profile/scan')),ListTile(leading:const Icon(Icons.logout),title:const Text('Вийти'),onTap:()=>ref.read(authProvider.notifier).logout()),
]);}}
class SettingsScreen extends ConsumerWidget { const SettingsScreen({super.key}); @override Widget build(BuildContext c,WidgetRef ref)=>ListView(padding:const EdgeInsets.all(24),children:[Text('Налаштування',style:Theme.of(c).textTheme.headlineSmall),SwitchListTile(title:const Text('Темна тема'),value:ref.watch(themeProvider),onChanged:(v)=>ref.read(themeProvider.notifier).state=v)]);}
class SecurityScreen extends StatelessWidget { const SecurityScreen({super.key}); @override Widget build(BuildContext c)=>const ListView(padding:EdgeInsets.all(24),children:[Text('Безпека',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800)),SizedBox(height:14),Card(child:ListTile(leading:Icon(Icons.verified_user_outlined),title:Text('Демо-підтвердження'),subtitle:Text('Сесія локальна, реального бекенду немає.')))]);}
