import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../providers/app_providers.dart';

class ChatsListScreen extends ConsumerStatefulWidget { const ChatsListScreen({super.key}); @override ConsumerState<ChatsListScreen> createState()=>_ChatsState(); }
class _ChatsState extends ConsumerState<ChatsListScreen> { String q=''; @override Widget build(BuildContext c){final chats=ref.watch(chatsProvider).where((x)=>x.name.toLowerCase().contains(q.toLowerCase())).toList(); return ListView(padding:const EdgeInsets.all(24),children:[Text('Чати',style:Theme.of(c).textTheme.headlineSmall!.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:4),Text('Спілкування школи',style:Theme.of(c).textTheme.bodyMedium),const SizedBox(height:18),TextField(onChanged:(v)=>setState(()=>q=v),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Пошук чатів')),const SizedBox(height:12),...chats.map((x)=>Card(child:ListTile(leading:CircleAvatar(child:Text(x.name.substring(0,1))),title:Text(x.name),subtitle:Text(x.lastMessage??''),trailing:x.unreadCount>0?Badge(label:Text('${x.unreadCount}')):null,onTap:()=>context.go('/home/chats/${x.id}'))))]);}}
class ChatScreen extends ConsumerStatefulWidget { const ChatScreen({super.key,required this.chatId}); final String chatId; @override ConsumerState<ChatScreen> createState()=>_ChatState(); }
class _ChatState extends ConsumerState<ChatScreen> { final ctrl=TextEditingController(); @override Widget build(BuildContext c){final chat=ref.watch(chatsProvider).firstWhere((x)=>x.id==widget.chatId); final msgs=ref.watch(messagesProvider(widget.chatId)); return Column(children:[
  ListTile(leading:IconButton(onPressed:()=>context.go('/home/chats'),icon:const Icon(Icons.arrow_back)),title:Text(chat.name,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${chat.membersCount} учасників')),
  Expanded(child:ListView.builder(reverse:true,padding:const EdgeInsets.all(16),itemCount:msgs.length,itemBuilder:(c,i){final m=msgs[i];final own=m.authorId=='session';return Align(alignment:own?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.symmetric(vertical:4),padding:const EdgeInsets.all(12),constraints:BoxConstraints(maxWidth:MediaQuery.sizeOf(c).width*.72),decoration:BoxDecoration(color:own?Theme.of(c).colorScheme.primary:Theme.of(c).colorScheme.surface,borderRadius:BorderRadius.circular(16),border:Border.all(color:Theme.of(c).colorScheme.outline)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(!own)Text(m.authorName,style:TextStyle(color:Theme.of(c).colorScheme.primary,fontWeight:FontWeight.w700,fontSize:12)),Text(m.text,style:TextStyle(color:own?Colors.white:null)),if(m.reactions.isNotEmpty)Text('❤️ ${m.reactions['❤️']??0}   👍 ${m.reactions['👍']??0}',style:const TextStyle(fontSize:11))])));})),
  SafeArea(top:false,child:Padding(padding:const EdgeInsets.all(10),child:Row(children:[Expanded(child:TextField(controller:ctrl,decoration:const InputDecoration(hintText:'Повідомлення...',prefixIcon:Icon(Icons.reply)))),IconButton(onPressed:()=>ctrl.clear(),icon:const Icon(Icons.send))])))
]);}}
class CommunitiesScreen extends StatelessWidget { const CommunitiesScreen({super.key}); @override Widget build(BuildContext c)=>_SimplePage(title:'Спільноти',items:['Шаховий клуб','Робототехніка','Медіацентр','Волонтерський клуб']);}
class NewsScreen extends ConsumerWidget { const NewsScreen({super.key}); @override Widget build(BuildContext c,WidgetRef ref)=>_SimplePage(title:'Новини',items:ref.watch(newsProvider).map((x)=>x.title).toList());}
class _SimplePage extends StatelessWidget { const _SimplePage({required this.title,required this.items}); final String title; final List<String> items; @override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(24),children:[Text(title,style:Theme.of(c).textTheme.headlineSmall!.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:14),...items.map((x)=>Card(child:ListTile(title:Text(x),subtitle:const Text('Демонстраційний локальний контент'),leading:const Icon(Icons.auto_awesome_outlined))))]);}
